### ISSUE TITLE
template finder don't work with ansible extension

### ISSUE THREAD

**Issue by alex-left** [ArtyMaury/template-finder#12]
The official ansible extension doesn't have autocomplete for variables outside from opened file, so this extension is very useful but don't work at the same time. ¿It's possible that?

**Comment by ArtyMaury** [comment]
Hello,
Sorry about the long response time. I'm not sure I understood your problem, is it a request for an autocomplete feature or a compatibility bug with the Ansible extension ?

**Comment by alex-left** [comment]
Hi Art, thanks for all. This would be a request for a compatibility with ansible extension.

**Comment by ArtyMaury** [comment]
Hi Alex,
Along with a lot of the users, I'm using the ansible extension and it works. So I guess it is not the issue.
What are the effects of your problem? is there no coloration at all, or does template-finder does find some variables ?
Can you activate the vscode dev tools (help menu) and see if there is an error in the console?

**Comment by alex-left** [comment]
Ok, maybe was anothe kind of problem. I will try again and investigate more deep before reporting you. I will tell you any discovery. thanks for your attention
