### ISSUE TITLE
Activation Template Finder for j2 extension files

### ISSUE THREAD

**Issue by lesgaillardus** [ArtyMaury/template-finder#13]
It would be useful to take into account the extensions * .j2 (jinja2) in which there are variables Ansible

**Comment by ArtyMaury** [comment]
Do you mean variables declared in a j2 file that really contains yaml? I don't get this file extension, it only hides the true content of the file and prevents your idea from helping you.

**Comment by ArtyMaury** [comment]
As discussed together, .j2 files are taken into account, it was a temporary glitch.
