### ISSUE TITLE
Support files with the extension ".yaml"

### ISSUE THREAD

**Issue by Demon-DK** [ArtyMaury/template-finder#14]
**Are there any plans to add support for ".yaml" files extension ?**
At least via manual settings in general **settings.json** VSCODE configuration.

I have a project with more than 20K files and they are all have "**.yaml**" extension and without this support this plugin are useless for a while.
And definetely to make bulk rename of all them it's not a solution at all because will lead to plenty of git commits with the deletion off all files and creating a new ones with the other extension.

**Comment by ArtyMaury** [comment]
Hello,
My bad, I forgot there was 2 extensions for yaml files.
I'll add the support in the next release.
