### ISSUE TITLE
does not work for nested dictionaries

### ISSUE THREAD

**Issue by uocxp** [ArtyMaury/template-finder#6]
fist of all thanks a lot for this plugin. I was waiting for a long time for a similar one because it is really hard to trace the variable values in ansible as I didn't find any go-to-definition tool that works with ansible.
It would be nice though if one can get the values of a nested array.

```
certbot_certs:
  - email: admin@admin.com
    domains:
      - foo.example.com
```
![image](https://user-images.githubusercontent.com/8387383/64025078-350c8500-cb3c-11e9-8160-b2d1221c1263.png)

for a such dictionary it's not possible to get the value of `email` for example.

Also it's not possible to show the values of for-each loop variables  jinja2 template
![image](https://user-images.githubusercontent.com/8387383/64025644-6fc2ed00-cb3d-11e9-9440-deca99646d76.png)

**Comment by ArtyMaury** [comment]
Hi uocxp, thanks for your feedback, I'm glad to see you like the extension!

About the first feature, it's quite hard to do I have to say, there's tons of ways to loop over a list in ansible, each with a different syntax (cf [ansible doc](https://docs.ansible.com/ansible/2.4/playbooks_loops.html)) and as I never found an ansible parsing engine, I'd have to handle them all myself. I'd be happy to help anyone who wants to do it, but it is too much work by myself.

The second feature request is more manageable, even if there is no jinja parsing engine either there is only one possible syntax in jinja2. I'll try and include that in the next version.
